/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RiskAnalysisRouteImport } from './routes/risk-analysis'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as CasesNewRouteImport } from './routes/cases.new'
import { Route as EvidenceIndexRouteImport } from './routes/evidence.index'
import { Route as EvidenceUploadRouteImport } from './routes/evidence.upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskAnalysisRoute = RiskAnalysisRouteImport.update({
  id: '/risk-analysis',
  path: '/risk-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesNewRoute = CasesNewRouteImport.update({
  id: '/cases/new',
  path: '/cases/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceIndexRoute = EvidenceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EvidenceRoute,
} as any)
const EvidenceUploadRoute = EvidenceUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => EvidenceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/evidence': typeof EvidenceRouteWithChildren
  '/network': typeof NetworkRoute
  '/reports': typeof ReportsRoute
  '/risk-analysis': typeof RiskAnalysisRoute
  '/timeline': typeof TimelineRoute
  '/cases/new': typeof CasesNewRoute
  '/evidence/upload': typeof EvidenceUploadRoute
  '/evidence/': typeof EvidenceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/network': typeof NetworkRoute
  '/reports': typeof ReportsRoute
  '/risk-analysis': typeof RiskAnalysisRoute
  '/timeline': typeof TimelineRoute
  '/cases/new': typeof CasesNewRoute
  '/evidence/upload': typeof EvidenceUploadRoute
  '/evidence': typeof EvidenceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/evidence': typeof EvidenceRouteWithChildren
  '/network': typeof NetworkRoute
  '/reports': typeof ReportsRoute
  '/risk-analysis': typeof RiskAnalysisRoute
  '/timeline': typeof TimelineRoute
  '/cases/new': typeof CasesNewRoute
  '/evidence/upload': typeof EvidenceUploadRoute
  '/evidence/': typeof EvidenceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/evidence'
    | '/network'
    | '/reports'
    | '/risk-analysis'
    | '/timeline'
    | '/cases/new'
    | '/evidence/upload'
    | '/evidence/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/network'
    | '/reports'
    | '/risk-analysis'
    | '/timeline'
    | '/cases/new'
    | '/evidence/upload'
    | '/evidence'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/evidence'
    | '/network'
    | '/reports'
    | '/risk-analysis'
    | '/timeline'
    | '/cases/new'
    | '/evidence/upload'
    | '/evidence/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  EvidenceRoute: typeof EvidenceRouteWithChildren
  NetworkRoute: typeof NetworkRoute
  ReportsRoute: typeof ReportsRoute
  RiskAnalysisRoute: typeof RiskAnalysisRoute
  TimelineRoute: typeof TimelineRoute
  CasesNewRoute: typeof CasesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-analysis': {
      id: '/risk-analysis'
      path: '/risk-analysis'
      fullPath: '/risk-analysis'
      preLoaderRoute: typeof RiskAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/new': {
      id: '/cases/new'
      path: '/cases/new'
      fullPath: '/cases/new'
      preLoaderRoute: typeof CasesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence/': {
      id: '/evidence/'
      path: '/'
      fullPath: '/evidence/'
      preLoaderRoute: typeof EvidenceIndexRouteImport
      parentRoute: typeof EvidenceRoute
    }
    '/evidence/upload': {
      id: '/evidence/upload'
      path: '/upload'
      fullPath: '/evidence/upload'
      preLoaderRoute: typeof EvidenceUploadRouteImport
      parentRoute: typeof EvidenceRoute
    }
  }
}

interface EvidenceRouteChildren {
  EvidenceUploadRoute: typeof EvidenceUploadRoute
  EvidenceIndexRoute: typeof EvidenceIndexRoute
}

const EvidenceRouteChildren: EvidenceRouteChildren = {
  EvidenceUploadRoute: EvidenceUploadRoute,
  EvidenceIndexRoute: EvidenceIndexRoute,
}

const EvidenceRouteWithChildren = EvidenceRoute._addFileChildren(
  EvidenceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  EvidenceRoute: EvidenceRouteWithChildren,
  NetworkRoute: NetworkRoute,
  ReportsRoute: ReportsRoute,
  RiskAnalysisRoute: RiskAnalysisRoute,
  TimelineRoute: TimelineRoute,
  CasesNewRoute: CasesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
